### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by napoAI** [instant-high/wav2lip-onnx-HQ#8]
Hello, 

How can I get temp.wav ?

FileNotFoundError: [Errno 2] No such file or directory: 'temp/temp.wav'

This is where I am: 

Running on cuda
2024-10-30 08:10:05.3451506 [E:onnxruntime:Default, provider_bridge_ort.cc:1304 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Reading video frames...
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Reading frames....
1673 Number of frames used for inference: 1674 / ~ 3023 mb memory usage
Extracting raw audio...
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\audio.py:10: UserWarning: PySoundFile failed. Trying audioread instead.
  return librosa.core.load(path, sr=sr)[0]
C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
Traceback (most recent call last):
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\librosa\core\audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\librosa\core\audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'temp/temp.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\inference_onnxModel.py", line 633, in <module>
    main()
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\inference_onnxModel.py", line 400, in main
    wav = audio.load_wav(args.audio, 16000)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\librosa\core\audio.py", line 184, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\librosa\util\decorators.py", line 59, in __wrapper
    return func(*args, **kwargs)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\librosa\core\audio.py", line 240, in __audioread_load
    reader = audioread.audio_open(path)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Users\napo_\Downloads\wav2lip-onnx-HQ-main\wav2lip-onnx-HQ-main\venv\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'temp/temp.wav'

**Comment by instant-high** [comment]
Install ffmpeg
